### ISSUE TITLE
Crashes when autofilling from Messages in iOS 12

### ISSUE THREAD

**Issue by ckorhonen** [gkueny/react-native-pin-code#12]
I'm using this component to implement a verification flow for phone numbers, delivering the code by SMS.

iOS12 has new functionality, [offering AutoFill as a quick type suggestion on the native keyboard](https://www.macrumors.com/how-to/use-secure-code-autofill-ios-12-macos-mojave/). Currently, this will trigger a crash with the following error:

```
undefined is not an object (evaluating 'this.textInputsRefs[e].focus')
```

<img width="809" alt="screen shot 2018-08-28 at 9 14 00 am" src="https://user-images.githubusercontent.com/39121/44725193-c321db80-aaa2-11e8-8010-57f55b58892d.png">

**Comment by gkueny** [comment]
fix in #13
