### ISSUE TITLE
React Native 0.54 iOS Backspace Issues

### ISSUE THREAD

**Issue by ckorhonen** [gkueny/react-native-pin-code#14]
Adding this to save anyone else pulling their hair out. If anyone is using 0.54-55 of React Native on iOS and encounters a specific issue relating to backspacing then this is likely cause: https://github.com/facebook/react-native/issues/18374

**The Issue**
* Enter `1`, `2`, `3`. (Should Look like `1 2 3`.)
* Hit Backspace.  (Should Look like `1 2`.)
* Enter `4`. (Should Look like `1 2 4`. Actually looks like `1 `.
* Enter more digits and it gets progressively crazier.

**Fix**
Replace the `onKeyPress` method
```
  onKeyPress(e){
    if (e.nativeEvent.key === 'Backspace'){
      // Nasty bug, fixed in RN .56 which caused extra backspace events.
      // https://github.com/facebook/react-native/issues/18374 Ack!
      // Return if duration between previous key press and backspace is less than 20ms
      if (Math.abs(this.lastKeyEventTimestamp - e.timeStamp) < 20) return;
      const { edit } = this.state;
      const toFocus = edit > 0 ? edit - 1 : 0;
      this.focus(toFocus);
    } else {
      // Record non-backspace key event time stamp
      this.lastKeyEventTimestamp = e.timeStamp;
    }
  }
```

This is apparently fixed in 0.56 so not sure it is worth a PR, but hopefully, this helps someone!

**Comment by gkueny** [comment]
Hi @ckorhonen ,

thank's for the report ! 
If it's fixed with **RN 0.56**  I don't think it's worth a PR.

So, if someone run into this issue, I recommend to upgrade to RN >= 0.56 or to use @ckorhonen solution.
