### ISSUE TITLE
Not clear input fields on iOS

### ISSUE THREAD

**Issue by dalba1992** [gkueny/react-native-pin-code#16]
Tried much time on iOS.
But after filling all inputs, it focused to the first field but not clearing the last field.
I think this is a bug of this component.
![image](https://user-images.githubusercontent.com/20521231/45068721-b5112380-b07d-11e8-9b8e-de3575a5e9e7.png)

**Comment by gkueny** [comment]
Hi @dalba1992,

Thanks for your report. I will publish a fix as soon as possible.

**Comment by gkueny** [comment]
can you test with  :  **react-native-pin-code@beta** before I publish a new release ?

```bash
$  npm i --save react-native-pin-code@beta
```

**Comment by gkueny** [comment]
Fixed for me in [v0.5.1](https://github.com/gkueny/react-native-pin-code/releases/tag/v0.5.1).

Feel free to re-open issue if not.

**Comment by dalba1992** [comment]
Thank you, @gkueny 
It's working well

**Comment by gkueny** [comment]
@dalba1992 ,

I wil check that tonight

**Comment by gkueny** [comment]
@dalba1992 ,

I can not reproduce your issue. 
I released a beta version with a fix which (I hope) can fix your issue.

Please test with latest beta version (`0.5.2@beta`)

```bash
$  npm i --save react-native-pin-code@beta
```

If this still not okey for you, please show me how  you use the __PinCode__ component.

**Comment by gkueny** [comment]
(I case of success, inputs will be not cleared.
If you want to, you have to call `clean` function.)

**Comment by gkueny** [comment]
I close this issue @dalba1992 

Feel free to re-open.
