### ISSUE TITLE
Can I use the plugin only for input, and have the methods complete? 

### ISSUE THREAD

**Issue by hugomosh** [gkueny/react-native-pin-code#2]
Can I use the plugin only for input, and have the methods complete( i.e., when the user fill the nth digitis) dispatch a function

**Comment by gkueny** [comment]
No.
The plugin focus on pin code, and for that, callback is fired only if user input match your defined pin code.

**Comment by rubinim1995** [comment]
i want to give two input 
<CodePin

code='',
code='',
/>

is it possible?
