### ISSUE TITLE
this.ref.clean() not clearing first box

### ISSUE THREAD

**Issue by whitney162** [gkueny/react-native-pin-code#22]
I am working on an android app and when I call this.ref.clean() in the checkPinCode function prop, it clears all the boxes except the first one and focus on the second one. Any idea how to fix this?

**Comment by gkueny** [comment]
Hi @whitney162,

Which version of CodePin do you use ?

**Comment by whitney162** [comment]
@gkueny I'm using 0.5.1

**Comment by whitney162** [comment]
I update to version 0.5.3 and I'm still having the same issue

**Comment by whitney162** [comment]
Nevermind, it works correctly if I do:
`                                             callback(true);
                                              this.ref.clean();`

Instead of:
                             `                                             this.ref.clean();
                                             callback(true);`

**Comment by gkueny** [comment]
an other way is to use `success` props.

```js
<CodePin
    checkPinCode={ (code, callback) => callback(true) }
    success={ () => this.ref.clean() } // ensure that CodePin internal state is clean
/>

```

**Comment by gkueny** [comment]
@whitney162 ,
an other way is to use `success` props.

```js
<CodePin
    checkPinCode={ (code, callback) => callback(true) }
    success={ () => this.ref.clean() } // ensure that CodePin internal state is clean
/>

```
