### ISSUE TITLE
two default code pin is needed

### ISSUE THREAD

**Issue by rubinim1995** [gkueny/react-native-pin-code#5]
if i want to give two set of code .. what i will do?
eg:-)
<CodePin
code='5665'
code='4678'
/>
for this two it will call success

**Comment by gkueny** [comment]
Hello ! 

With 0.3.0 version you can implement your check function with `checkPinCode` prop : 

```js
<CodePin
    code="fake_code_needed_by_component"

    number={4} // You must pass number prop, it will be used to display 4 (here) inputs, 
                        // so all your codes must have size : 4 (for instance: 1234, 1254)

  checkPinCode={(code, callback) => callback(code === '1234' || code === '1235' )}

  // other props
/>
```

With this code, '1234' and '1235' will be recognized by CodePin component.

**Comment by gkueny** [comment]
prop `code` is required by the component, but if you pass checkPinCode `prop`,  CodePin won't use `code` but it will call `checkPinCode(code_fill_by_user, callbackFunction)`. 

it's weird indeed but it will be fixed in a future version to pass only prop `code` or prop `checkPinCode`.

**Comment by rubinim1995** [comment]
thanks...its worked..
